spring:
  application:
    name: oauth2

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  apple:
    key-id:  ${APPLE_KEY_ID}
    team-id:  ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
    private-key-path: ${APPLE_PRIVATE_KEY_PATH}
    redirect-uri: ${APPLE_REDIRECT_URI}
    audience-uri: "https://appleid.apple.com"
    user-info-uri: https://appleid.apple.com/auth/token
