spring:
  application:
    name: oauth2
  profiles:
    active: comp

---
spring:
  config:
    activate:
      on-profile: server

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      minimum-idle: ${DB_MINIMUM_IDLE}
      maximum-pool-size: ${DB_MAXIMUM_SIZE}
      idle-timeout: ${DB_IDLE_TIMEOUT}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

oauth2:
  apple:
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
    private-key-path: ${APPLE_PRIVATE_KEY_PATH}
    redirect-uri: ${APPLE_REDIRECT_URI}
    jwks-uri: https://appleid.apple.com/auth/keys
    audience-uri: https://appleid.apple.com
    user-info-uri: https://appleid.apple.com/auth/token
  kakao:
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
  jwt:
    secret: ${OAUTH2_JWT_SECRET}
    access-token-expiry: ${OAUTH2_JWT_ACCESS_TOKEN_EXPIRY}
    refresh-token-expiry: ${OAUTH2_JWT_REFRESH_TOKEN_EXPIRY}

---
spring:
  config:
    activate:
      on-profile: comp
    import: optional:dotenv[.env]

  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

oauth2:
  apple:
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
    private-key-path: ${APPLE_PRIVATE_KEY_PATH}
    redirect-uri: ${APPLE_REDIRECT_URI}
    jwks-uri: https://appleid.apple.com/auth/keys
    audience-uri: https://appleid.apple.com
    user-info-uri: https://appleid.apple.com/auth/token
  kakao:
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
  jwt:
    secret: ${OAUTH2_JWT_SECRET}
    access-token-expiry: ${OAUTH2_JWT_ACCESS_TOKEN_EXPIRY}
    refresh-token-expiry: ${OAUTH2_JWT_REFRESH_TOKEN_EXPIRY}


---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:goods
    username: user
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

oauth2:
  apple:
    key-id: 11
    team-id: 11
    client-id: 11
    private-key-path: 11
    redirect-uri: 11
    jwks-uri: https://appleid.apple.com/auth/keys
    audience-uri: https://appleid.apple.com
    user-info-uri: https://appleid.apple.com/auth/token
  kakao:
    client-secret: 11
    redirect-uri: 11
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: 11
    client-secret: 11
    redirect-uri: 11
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
  jwt:
    secret: U2VjdXJlS2V5Rm9yU3ByaW5nQm9vdEFwcExldEV4YW1wbGU=
    access-token-expiry: 30m
    refresh-token-expiry: 30d